### ISSUE TITLE
RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: undefined

### ISSUE THREAD

**Issue by emi911** [jigar-sable/flipkart-mern#12]

**Comment by emi911** [comment]
Server running on http://localhost:4000
Mongoose Connected
RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: undefined
    at ServerResponse.writeHead (node:_http_server:352:11)
    at ServerResponse._implicitHeader (node:_http_server:338:8)
    at write_ (node:_http_outgoing:945:9)
    at ServerResponse.end (node:_http_outgoing:1056:5)
    at ServerResponse.send (C:\Users\Rapid\Desktop\1c\flipkart-mern\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (C:\Users\Rapid\Desktop\1c\flipkart-mern\node_modules\express\lib\response.js:278:15)
    at module.exports (C:\Users\Rapid\Desktop\1c\flipkart-mern\backend\middlewares\error.js:31:32)
    at Layer.handle_error (C:\Users\Rapid\Desktop\1c\flipkart-mern\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (C:\Users\Rapid\Desktop\1c\flipkart-mern\node_modules\express\lib\router\index.js:326:13)
    at C:\Users\Rapid\Desktop\1c\flipkart-mern\node_modules\express\lib\router\index.js:286:9
