### ISSUE TITLE
this is issue i am facing.......

### ISSUE THREAD

**Issue by 18-Deepa-02** [jigar-sable/flipkart-mern#7]
] RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: undefined
[0]     at new NodeError (node:internal/errors:405:5)
[0]     at ServerResponse.writeHead (node:_http_server:347:11)
[0]     at ServerResponse._implicitHeader (node:_http_server:338:8)
[0]     at write_ (node:_http_outgoing:915:9)
[0]     at ServerResponse.end (node:_http_outgoing:1026:5)
[0]     at ServerResponse.send (D:\flipkart-mern-master\node_modules\express\lib\response.js:232:10)
[0]     at ServerResponse.json (D:\flipkart-mern-master\node_modules\express\lib\response.js:278:15)
[0]     at module.exports (D:\flipkart-mern-master\backend\middlewares\error.js:31:32)
[0]     at Layer.handle_error (D:\flipkart-mern-master\node_modules\express\lib\router\layer.js:71:5)
[0]     at trim_prefix (D:\flipkart-mern-master\node_modules\express\lib\router\index.js:326:13)

**Comment by 18-Deepa-02** [comment]
] RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: undefined
[0]     at new NodeError (node:internal/errors:405:5)
[0]     at ServerResponse.writeHead (node:_http_server:347:11)
[0]     at ServerResponse._implicitHeader (node:_http_server:338:8)
[0]     at write_ (node:_http_outgoing:915:9)
[0]     at ServerResponse.end (node:_http_outgoing:1026:5)
[0]     at ServerResponse.send (D:\flipkart-mern-master\node_modules\express\lib\response.js:232:10)
[0]     at ServerResponse.json (D:\flipkart-mern-master\node_modules\express\lib\response.js:278:15)
[0]     at module.exports (D:\flipkart-mern-master\backend\middlewares\error.js:31:32)
[0]     at Layer.handle_error (D:\flipkart-mern-master\node_modules\express\lib\router\layer.js:71:5)
[0]     at trim_prefix (D:\flipkart-mern-master\node_modules\express\lib\router\index.js:326:13)

**Comment by GeoXhacker** [comment]
can you provide a context on how you faced this error?
